### ISSUE TITLE
DOMException: querySelectorAll is not a valid selector in latest Firefox

### ISSUE THREAD

**Issue by sidvishnoi** [KittyGiraudel/focusable-selectors#12]
`:has` (introduced in https://github.com/KittyGiraudel/focusable-selectors/pull/9) doesn't have a great browser support as of now. Mainly, it's not supported in Firefox 109 (latest).
Please consider removing the selector. I don't think that selector is possible without `:has`.

Workaround: manually remove the selector with `:has`.

**Comment by KittyGiraudel** [comment]
Hey Sid! 

Thank you for opening an issue. You’re right, the `:has` pseudo-class doesn’t have the best support at the moment. That being said, does it cause any issue to keep that selector in? Ultimately, it will be discard if not understood by the browser, which seems like a safe behavior.

Do you want to share more information about your use-case?

**Comment by sidvishnoi** [comment]
> Ultimately, it will be discard if not understood by the browser, which seems like a safe behavior.

That's the issue. This doesn't happen if we pass it to querySelector. It throws an invalid selector DOMException.

Try running following in Firefox devtools console:
```js
document.querySelector(`details:not(:has(> summary))`)
```

**Comment by KittyGiraudel** [comment]
Oooooh, I see. Yeah, that makes sense. A workaround would be to use every selector individually and wrap that with a try/catch, but maybe it’s better for focusable-selectors to skip on `:has` for now.

**Comment by KittyGiraudel** [comment]
Done with 0.7.0.

**Comment by sidvishnoi** [comment]
Thanks for the quick turnaround @KittyGiraudel!

**Comment by kirkobyte** [comment]
`:has` now has baseline support, so I think can be safely added 🎉 https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Selectors/:has
