### ISSUE TITLE
Getting not a valid selector error using package in Vitest 

### ISSUE THREAD

**Issue by sebnitu** [KittyGiraudel/focusable-selectors#17]
I'm using this package in one of my projects and just recently started seeing a bunch of test errors being thrown after updating the version of `nwsapi` which gets used by `jsdom`. Are you aware of any workarounds for this? I realize this isn't actually an issue with this package, it works great! Just having a hard time figuring out a fix.

I was previously overriding the version to `2.2.2` which didn't throw these errors but recently needed to add suport for `:focus-visible` which only exists in newer versions of `nwsapi`.

```
SyntaxError: '[inert] *):not([tabindex^="-"]):not(:disabled' is not a valid selector
 ❯ emit node_modules/nwsapi/src/nwsapi.js:575:17
 ❯ Object._matches [as match] node_modules/nwsapi/src/nwsapi.js:1417:9
 ❯ Array.Resolver node_modules/nwsapi/src/nwsapi.js:777:17
 ❯ collect node_modules/nwsapi/src/nwsapi.js:1573:21
 ❯ Object._querySelectorAll [as select] node_modules/nwsapi/src/nwsapi.js:1528:36
 ❯ HTMLDivElementImpl.querySelectorAll node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:78:26
 ❯ HTMLDivElement.querySelectorAll node_modules/jsdom/lib/jsdom/living/generated/Element.js:1119:58
```

**Comment by KittyGiraudel** [comment]
Hello! Looks like it’s related to https://github.com/dperini/nwsapi/issues/72, which they decided to close last year. :(

**Comment by sebnitu** [comment]
Aww, that's a bummer. No worries, I'll try and find a workaround. Thank you very much for the reply and your work on this project!

**Comment by KittyGiraudel** [comment]
Wait, actually I just checked the code, and the only selector using `:has()` is commented out, so it cannot be that. What you could do is copy and paste the array of selectors in your project and comment them out one by one to find the faulty one. And then we can open an issue on the nswapi repo.

**Comment by sebnitu** [comment]
Oh, good catch! I was able to narrow it down to these three selectors:

```js
const focusableSelectors = [
  `button${notInert}${notNegTabIndex}${notDisabled}`, // BAD
  `[contenteditable]${notInert}${notNegTabIndex}`, // BAD
  `[tabindex]${notInert}${notNegTabIndex}`, // BAD
]
```

It's not really clear to me why these are a problem tho? They're all doing very similar things to the other selectors.

**EDIT**

It looks like it's specifically the `${notInert}` portion causing the error.

```js
const notInert = ':not([inert]):not([inert] *)';
```

**Comment by KittyGiraudel** [comment]
Could you try removing `:not([inert] *)`? I suspect it doesn’t support complex selectors.

**Comment by sebnitu** [comment]
Yup, that fixed it! It's odd because the other places you were using `:not([inert] *)` were working as expected, but just `button`, `[contenteditable]` and `[tabindex]` were causing the error :-/

**Comment by KittyGiraudel** [comment]
I would recommend you open an issue on the nwsapi repository with the fault selector so they can explore the problem.

**Comment by sebnitu** [comment]
Will do that for sure, thank you!
